---
title: "work05"
author: "qinluoao"
date: "2017/07/30"
output:
  html_document:
    highlight: haddock
  pdf_document:
    highlight: tango
    includes:
      in_header: header.tex
    keep_tex: yes
    latex_engine: xelatex
  word_document: default
---

```{r}
# Get 'plotly'packages   data.table,httpuv,plotly
library(plotly)
# The diamonds dataset
data(diamonds)
str(diamonds)

# A firs scatterplot has been made for you
plot_ly(diamonds, x = ~carat, y = ~price)

# Replace ___ with the correct vector
plot_ly(diamonds, x = ~carat, y = ~price, color = ~carat)
        
# Replace ___ with the correct vector
plot_ly(diamonds, x = ~carat, y = ~price, color = ~carat, size = ~carat)
# 3.The interactive bar chart
library(dplyr)   #count()  %>%管道函数啦，就是把左件的值发送给右件的表达式，并作为右件表达式函数的第一个参数
# Calculate the numbers of diamonds for each cut<->clarity combination
diamonds_bucket <- diamonds %>% count(cut, clarity)

# Replace ___ with the correct vector
plot_ly(diamonds_bucket, x = ~cut, y = ~n, type = "bar", color = ~clarity)
#4.From the bar to the box: the box plot
# The Non Fancy Box Plot
plot_ly(y = ~rnorm(50), type = "box")

# The Fancy Box Plot
plot_ly(diamonds, y = ~price, color = ~cut, type = "box")

# The Super Fancy Box Plot
plot_ly(diamonds, x = ~cut, y =~price, color =~clarity, type ="box") %>%
  layout(boxmode = "group")
#5.Visualizing volcano data
#'scatter', 'bar', 'box', 'heatmap', 'histogram', 'histogram2d', 'histogram2dcontour', 'pie', #'contour', 'scatter3d', 'surface', 'mesh3d', 'scattergeo', 'choropleth', 'scattergl', #'scatterternary', 'scattermapbox', 'area'
## Load the `plotly` library
library(plotly)
# Your volcano data
str(volcano)
# The heatmap
plot_ly(z=~volcano, type = "heatmap")
# The 3d surface map
plot_ly(z=~volcano, type = "surface")

#6.ggplot2, the interactive dimension
#you can now convert your ggplot2 plots into interactive, web-based versions. 
# Create the ggplot2 graph
ggplot(mtcars, aes(x =wt, y = mpg, col = cyl)) +
  geom_point()

# Make your plot interactive
ggplotly()


#7.Sliding into the final exercise
## Monthly totals of accidental deaths in the USA
plot_ly(x = time(USAccDeaths), y = USAccDeaths) %>% 
  add_lines() %>%
  rangeslider()

# Apple Stock Price
apple_stock_price=read.csv("F:/2017/r_data/apple_stock_price.csv",sep = ',',header = T)
str(apple_stock_price)

# Apple Stock Price With Rangeslider
plot_ly(apple_stock_price, x = ~Date) %>%
  add_lines(y = ~AAPL.Adjusted, name = "Apple") %>% 
  rangeslider() %>% 
  layout(
    title = "Stock Price Apple",
    xaxis = list(title = "Date"),
    yaxis = list(title = "Price"))

```
```{r}
#8.An interactive airport map
airport_traffic=read.csv("F:/2017/r_data/airport_traffic.csv",header = T,sep=",",fileEncoding = "utf-8")
# Most Trafficked US Airports
g <- list(scope = 'usa',showland = TRUE,landcolor = toRGB("gray95"))

plot_geo(airport_traffic, lat = ~lat, lon = ~long) %>%
  add_markers(
    text = ~paste(airport, city, state, paste("Arrivals:", cnt), sep = "<br />"),
    color = ~cnt, symbol = I("square"), size = I(8), hoverinfo = "text"
  ) %>%
  colorbar(title = "Incoming flights<br />February 2011") %>%
  layout(
    title = 'Most trafficked US airports<br />(Hover for airport)', geo = g
  )
#Based on the code of the "Most trafficked US airports map", create a world map that maps all commercial airports in the world (airports).
#For a map of the world, the scope is the world.
#Each airport should be represented by a circle and on hover you should see the AirportID, City and Country of that aiport.
#The color of the airport circle should depend on the country.
#
```




